services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: moedin
      POSTGRES_PASSWORD: moedin
      POSTGRES_DB: moedin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://moedin:moedin@db:5432/moedin_db
      JWT_SECRET: "troque_essa_senha_depois"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata: